server:
  port: 8087

spring:
  application:
    name: enterprise-service
  datasource:
    # URL Database riêng của service (Mô hình Database-per-service)
    url: jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/ecocycle_enterprise
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Tự động tạo bảng dựa trên Entity viết sẵn
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Khai báo với Service Registry (Khối 1 quản lý)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
